apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginxapp2
  labels:
    app: app2-nginx
  annotations:
   # Load Balancer Name
   alb.ingress.kubernetes.io/load-balancer-name: app2ingress
   alb.ingress.kubernetes.io/scheme: internet-facing
   # Health Check Settings
   alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
   alb.ingress.kubernetes.io/healthcheck-port: traffic-port
   alb.ingress.kubernetes.io/healthcheck-path: /app2/index.html
   alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
   alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
   alb.ingress.kubernetes.io/success-codes: '200'
   alb.ingress.kubernetes.io/healthy-threshold-count: '2'
   alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
spec:
  ingressClassName: my-aws-ingress-class # Ingress Class
  defaultBackend:
    service:
      name: app2-nginx-nodeport-service
      port:
        number: 80
 
